title: Toxic80L's Blog
description: "The quieter you become, the more you are able to hear."
author:
  name: "Toxic80L"
  email: "anonymous@anonymous.com"
  url: "https://toxic80l.github.io"

baseurl: /
source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Toxic80L"
year : "2024"
